baseURL = 'https://yourssto.github.io/'
languageCode = 'en-us'
title = 'Yours, Sto ʚɞ'
theme = 'new'
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  description = "Yours, Sto - The Blog"
  image = "/thumbnail.png"

